clear; close all; clc;

value = -1;
signed = 1;
integer = 11;
word_len = 32;
frac = word_len - integer - 1;
T = numerictype(signed,word_len,frac);
F = fimath('CastBeforeSum',true,...
           'MaxProductWordLength',word_len,...
           'MaxSumWordLength',word_len,...
           'OverflowAction','Wrap',...
           'ProductFractionLength',frac,...
           'RoundingMethod','Floor',...
           'ProductMode','SpecifyPrecision',...
           'ProductWordLength',word_len,...
           'RoundingMethod','Floor',...
           'SumFractionLength',frac,...
           'SumMode','SpecifyPrecision',...
           'SumWordLength',word_len);
fixed = fi(value, T)
fixed.bin